routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect(env('APP_URL'). '/login');
});


Auth::routes();


Route::middleware(['auth'])->namespace('Admin')->group(function () {
    Route::get('/admin/home', 'HomeController@index')->name('admin.home.index');
    Route::resource('/admin/user', 'UserController');
    Route::resource('/admin/product','ProductController');
    Route::resource('/admin/voucher','VoucherController');
    

});

app/Models/Voucher.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Voucher extends Model
{
    use HasFactory;
    
    protected $fillable = [
        'id', 'voucher_code','discount_amt'
    ];

    public function reserve()
    {
        return $this->belongsTo(Order::class);
    }
}

app/Http/Controllers/Admin/VoucherController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Voucher;
use App\Models\Access;
use App\Http\Requests\VoucherValidationRequest;

class VoucherController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       
        $vouchers = Voucher::all();
        return view('admin.voucher.index', compact('vouchers'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $vouchers = Voucher::all();
        return view('admin.voucher.addVoucher');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(VoucherValidationRequest $request)
    {
        $validated = $request->validated();

        $isExist = Voucher::where('voucher_code', $request->voucher_code)->first();
        if($isExist)
        {
            echo'Voucher Sudah Tersedia';
        }else{
            $model = new Voucher();
            $model->voucher_code = $request->voucher_code;
            $model->discount_amt = $request->discount_amt;
            
            if($model->save())
            {
                return redirect(route('voucher.index'));
            }
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $hasAccessUsers = $this->checkAccess();

        $vouchers = Voucher::findOrFail($id);
    
        return view('admin.voucher.showVoucher', compact('vouchers'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $hasAccessUsers = $this->checkAccess();

        $accesses = Access::all();
        $vouchers = Voucher::findOrFail($id);
    
        return view('admin.voucher.editVoucher', compact('vouchers'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $hasAccessUsers = $this->checkAccess();
        $vouchers = Voucher::findOrFail($id);

        $vouchers->voucher_code = $request->voucher_code;
        $vouchers->discount_amt = $request->discount_amt;
       
        $vouchers->save();
        return redirect(route('voucher.index'));

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $hasAccessUsers = $this->checkAccess();
        $vouchers = Voucher::findOrFail($id);
        if($vouchers->delete()){
            return redirect(route('voucher.index'));
        }
    }

    private function checkAccess()
    {
        $user = auth()->user();
        $accessId = $user->access_id;

        $redirect = 'Drupal';
        if($accessId === 1)
        {
            $redirect = 'menu admin';
        }
    }
}

resources/views/admin/voucher/addVoucher.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    Add Voucher
                    
                </div>
                <div class="card-body">
                    
                <form action="{{ route('voucher.store')}}" method="POST">
                    @csrf
                    <div class="mb-3">
                        <label class="form-label">ID</label>
                        <input type="text" class="form-control", name="id">
                        @if ($errors->has('id'))
                            <span>{{ $errors->first('id') }}</span>
                        @endif
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Voucher Code</label>
                        <input type="text" class="form-control", name="voucher_code">
                        @if ($errors->has('voucher_code'))
                            <span>{{ $errors->first('voucher_code') }}</span>
                        @endif
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Discount Amount</label>
                        <input type="bigInteger" class="form-control", name="discount_amt">
                        @if ($errors->has('discount_amt'))
                            <span>{{ $errors->first('discount_amt') }}</span>
                        @endif
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/voucher/editVoucher.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    Edit Voucher
                    
                </div>
                <div class="card-body">
                    
                <form action="{{ route('voucher.update', $vouchers->id )}}" method="POST">
                    @csrf
                    @method('PUT')
                    <div class="mb-3">
                        <label class="form-label">ID</label>
                        <input type="text" class="form-control" name="id" value="{{ $vouchers->id }}">
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Voucher Code</label>
                        <input type="text" class="form-control" name="voucher_code" value="{{ $vouchers->voucher_code }}">
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Discount Amount</label>
                        <input type="bigInteger" class="form-control" name="discount_amt" value="{{ $vouchers->discount_amt }}">
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/voucher/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container" id = "voucher-index">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    Vouchers
                    <a href="{{ route('voucher.create')}}" type="button" class="btn btn-primary" style="float: right">Add Voucher</a>
                </div>
                <div class="card-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">Id</th>
                                <th scope="col">Voucher Code</th>
                                <th scope="col">Discount Amount</th>
                                <th scope="col">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($vouchers as $item)
                            <tr>
                                <th scope="row">{{ $item->id }}</th>
                                <td>{{ $item->voucher_code}}</td>
                                <td>{{ $item->discount_amt }}</td>
                                
                                <td>
                                    <a href="{{ route('voucher.edit', ['voucher'=> $item->id]  )}}" type="button" class="btn btn-success">Edit</a>
                                    <a href="{{ route('voucher.show', $item->id )}}" type="button" class="btn btn-secondary">Show</a>
                                    
                                    <form action="{{ route('voucher.update', $item->id) }}" method="POST">
                                        @csrf
                                        @method('delete')
                                        <button type="submit" class="btn btn-danger">Delete</button>
                                    </form>
                                </td>
                            </tr>                               
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/voucher/showVoucher.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
    
    <div class="card shadow mb-4">
        <div class="card header py-3">
            <div class="row">
                <div class="col d-flex align-item-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">Users</h6>
                <div>
            </div>
        </div>
        <div class="card-body">

            <div class="form-body">
                <div class="row">
                    <div class="col-md-8">
                        <div class="form-group row">
                            <label class="col-md-2 label-control text-left">ID</label>
                            <div class="col-md-10">
                                <p>{{ $vouchers->id }}</p>
                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-body">
                <div class="row">
                    <div class="col-md-8">
                        <div class="form-group row">
                            <label class="col-md-2 label-control text-left">Voucher Code</label>
                            <div class="col-md-10">
                            <p>{{ $vouchers->voucher_code }}</p>
                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-body">
                <div class="row">
                    <div class="col-md-8">
                        <div class="form-group row">
                            <label class="col-md-2 label-control text-left">Discount Amount</label>
                            <div class="col-md-10">
                            <p>{{ $vouchers->discount_amt }}</p>
                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-body">
                <div class="row">
                    <div class="col-md-8">
                        <div class="form-group row">
                            <label class="col-md-2 label-control text-left"></label>
                            <div class="col-md-10">
                                <a type="btn" class="btn btn-md btn-secondary" href="{{ route('voucher.index') }}">Back</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
                
        </div>
    </div>
</div>
@endsection