routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect(env('APP_URL'). '/login');
});


Auth::routes();


Route::middleware(['auth'])->namespace('Admin')->group(function () {
    Route::get('/admin/home', 'HomeController@index')->name('admin.home.index');
    Route::resource('/admin/user', 'UserController');
    Route::resource('/admin/product','ProductController');
    Route::resource('/admin/voucher','VoucherController');
    

});

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;
    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'item', 'description', 'qty', 'price', 'image_url'
    ];

    public function images()
    {
        return $this->hasMany(Image::class);
    }

    public function cartDetails()
    {
        return $this->hasMany(cartDetails::class);
    }
}

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Product;
use App\Models\Voucher;
use App\Models\Access;
use App\Http\Requests\ProductValidationRequest;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       
        $Products = Product::all();
        return view('admin.product.index', compact('Products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $Products = Product::all();
        return view('admin.product.addProduct');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProductValidationRequest $request)
    {
        $validated = $request->validated();
        
        $isExist = Product::where('item', $request->item)->first();
        if($isExist)
        {
            echo'Product Tersedia';
        }else{
            $model = new Product();
            $model->item = $request->item;
            $model->description = $request->description;
            $model->qty = $request->qty;
            $model->price = $request->price;
            $model->image_url = $request->image_url;
            
            if($model->save())
            {
                return redirect(route('product.index'));
            }
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $hasAccessUsers = $this->checkAccess();

        $Products = Product::findOrFail($id);
    
        return view('admin.product.showProduct', compact('Products'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $hasAccessUsers = $this->checkAccess();

        $accesses = Access::all();
        $Products = Product::findOrFail($id);
    
        return view('admin.product.editProduct', compact('Products'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $hasAccessUsers = $this->checkAccess();
        $Products = Product::findOrFail($id);

        $Products->item = $request->item;
        $Products->description = $request->description;
        $Products->qty = $request->qty;
        $Products->price = $request->price;
        $Products->image_url = $request->image_url;
       
        $Products->save();
        return redirect(route('product.index'));

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $hasAccessUsers = $this->checkAccess();
        $Products = Product::findOrFail($id);
        if($Products->delete()){
            return redirect(route('product.index'));
        }
    }

    private function checkAccess()
    {
        $user = auth()->user();
        $accessId = $user->access_id;

        $redirect = 'Drupal';
        if($accessId === 1)
        {
            $redirect = 'menu admin';
        }
    }
}

resources/views/admin/product/addProduct.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    Add New Product
                </div>
                <div class="card-body">
                    
                <form action="{{ route('product.store')}}" method="POST">
                    @csrf
                    <div class="mb-3">
                        <label class="form-label">Product Name</label>
                        <input type="text" class="form-control" name="item">
                        @if ($errors->has('item'))
                            <span>{{ $errors->first('item') }}</span>
                        @endif
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Product Description</label>
                        <input type="text" class="form-control" name="description">
                        @if ($errors->has('description'))
                            <span>{{ $errors->first('description') }}</span>
                        @endif
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Stock</label>
                        <input type="integer" class="form-control" name="qty">
                        @if ($errors->has('qty'))
                            <span>{{ $errors->first('qty') }}</span>
                        @endif
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Unit Price</label>
                        <input type="integer" class="form-control" name="price">
                        @if ($errors->has('price'))
                            <span>{{ $errors->first('price') }}</span>
                        @endif
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Image Url</label>
                        <input type="text" class="form-control" name="image_url">
                        @if ($errors->has('image_url'))
                            <span>{{ $errors->first('image_url') }}</span>
                        @endif
                    </div>
                
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/product/editProduct.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    Edit Product
                    
                </div>
                <div class="card-body">
                    
                <form action="{{ route('product.update', $Products->id )}}" method="POST">
                    @csrf
                    @method('PUT')
                    <div class="mb-3">
                        <label class="form-label">Product Name</label>
                        <input type="text" class="form-control" name="item" value="{{ $Products->item }}">
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Product Description</label>
                        <input type="text" class="form-control" name="description" value="{{ $Products->description }}">
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Stock</label>
                        <input type="integer" class="form-control" name="qty" value="{{ $Products->qty }}">
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Unit Price</label>
                        <input type="integer" class="form-control" name="price" value="{{ $Products->price }}">
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Product Image</label>
                        <input type="text" class="form-control" name="image_url" value="{{ $Products->image_url }}">
                    </div>
                        
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/product/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container" id = "user-index">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    Products
                    <a href="{{ route('product.create')}}" type="button" class="btn btn-primary" style="float: right">Add Product</a>
                </div>
                <div class="card-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">No</th>
                                <th scope="col">Product Name</th>
                                <th scope="col">Product Description</th>
                                <th scope="col">Stock</th>
                                <th scope="col">Unit Price</th>
                                <th scope="col">Product Image</th>
                                <th scope="col">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($Products as $item)
                            <tr>
                                <th scope="row">{{ $item->id }}</th>
                                <td>{{ $item->item }}</td>
                                <td>{{ $item->description }}</td>
                                <td>{{ $item->qty }}</td>
                                <td>{{ $item->price }}</td>
                                <td><img src="{{ $item->image_url }}"  width="50" height="50"></td>
                                
                                <td>
                                    <a href="{{ route('product.edit', ['product'=> $item->id]  )}}" type="button" class="btn btn-success">Edit</a>
                                    <a href="{{ route('product.show', $item->id )}}" type="button" class="btn btn-secondary">Show</a>
                                    
                                    <form action="{{ route('product.update', $item->id) }}" method="POST">
                                        @csrf
                                        @method('delete')
                                        <button type="submit" class="btn btn-danger">Delete</button>
                                    </form>
                                </td>
                            </tr>                               
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/product/showProduct.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
    
    <div class="card shadow mb-4">
        <div class="card header py-3">
            <div class="row">
                <div class="col d-flex align-item-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">No</h6>
                <div>
            </div>
        </div>
        <div class="card-body">

            <div class="form-body">
                <div class="row">
                    <div class="col-md-8">
                        <div class="form-group row">
                            <label class="col-md-2 label-control text-left">Product Name</label>
                            <div class="col-md-10">
                                <p>{{ $Products->item }}</p>
                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-body">
                <div class="row">
                    <div class="col-md-8">
                        <div class="form-group row">
                            <label class="col-md-2 label-control text-left">Product Description</label>
                            <div class="col-md-10">
                            <p>{{ $Products->description }}</p>
                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-body">
                <div class="row">
                    <div class="col-md-8">
                        <div class="form-group row">
                            <label class="col-md-2 label-control text-left">Stock</label>
                            <div class="col-md-10">
                            <p>{{ $Products->qty }}</p>
                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-body">
                <div class="row">
                    <div class="col-md-8">
                        <div class="form-group row">
                            <label class="col-md-2 label-control text-left">Unit Price</label>
                            <div class="col-md-10">
                            <p>{{ $Products->price }}</p>
                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-body">
                <div class="row">
                    <div class="col-md-8">
                        <div class="form-group row">
                            <label class="col-md-2 label-control text-left">Product Image</label>
                            <div class="col-md-10">
                            <p>{{ $Products->image_url }}</p>
                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-body">
                <div class="row">
                    <div class="col-md-8">
                        <div class="form-group row">
                            <label class="col-md-2 label-control text-left"></label>
                            <div class="col-md-10">
                                <a type="btn" class="btn btn-md btn-secondary" href="{{ route('product.index') }}">Back</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
                
        </div>
    </div>
</div>
@endsection