routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect(env('APP_URL'). '/login');
});


Auth::routes();


Route::middleware(['auth'])->namespace('Admin')->group(function () {
    Route::get('/admin/home', 'HomeController@index')->name('admin.home.index');
    Route::resource('/admin/user', 'UserController');
    Route::resource('/admin/product','ProductController');
    Route::resource('/admin/voucher','VoucherController');
    

});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'access_id'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function access()
    {
        return $this->belongsTo(Access::class);
    }

    public function order()
    {
        return $this->hasMany(Order::class);
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\User;
use App\Models\Access;
use App\Http\Requests\UserValidationRequest;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $hasAccessUsers = $this->checkAccess();

        $users = User::all();
        return view('admin.user.index', compact('users', 'hasAccessUsers'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        
        $hasAccessUsers = $this->checkAccess();
        $accesses = Access::all();
        return view('admin.user.addUser', compact('accesses'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(UserValidationRequest $request)
    {
        $validated = $request->validated();
        
        $hasAccessUsers = $this->checkAccess();
        $isExist = User::where('email', $request->email)->first();
        if($isExist)
        {
            echo'Email Sudah Ada';
        }else{
            $model = new User();
            $model->name = $request->name;
            $model->email = $request->email;
            $model->password = password_hash("Rahasia", PASSWORD_BCRYPT);
            $model->access_id = $request->access_id;
            
            if($model->save())
            {
                return redirect(route('user.index'));
            }
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $hasAccessUsers = $this->checkAccess();

        $Users = User::findOrFail($id);
    
        return view('admin.user.showUser', compact('Users'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($user)
    {
        $hasAccessUsers = $this->checkAccess();

        $accesses = Access::all();
        $Users = User::findOrFail($user);
        return view('admin.user.editUser', compact('Users','accesses'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $hasAccessUsers = $this->checkAccess();
        $Users = User::findOrFail($id);

        $Users->name = $request->name;
        $Users->email = $request->email;
        $Users->access_id = $request->access_id;
       
        $Users->save();

        return redirect(route('user.index'));

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $hasAccessUsers = $this->checkAccess();
        $Users = User::findOrFail($id);
        if($Users->delete()){
            return redirect(route('user.index'));
        }
    }

    private function checkAccess()
    {
        // $userAccess = auth()->user()->access->name ?? null;
        // if($userAccess !== 'Admin')
        // {
        //     abort(404);
        // }

        // return true;
        $user = auth()->user();
        $accessId = $user->access_id;

        $redirect = 'Drupal';
        if($accessId === 1)
        {
            $redirect = 'menu admin';
        }
    }
}

resources/views/admin/user/addUser.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    Add New User
                    
                </div>
                <div class="card-body">
                    
                <form action="{{ route('user.store')}}" method="POST">
                    @csrf
                    <div class="mb-3">
                        <label class="form-label">Name</label>
                        <input type="text" class="form-control", name="name">
                        @if ($errors->has('name'))
                            <span>{{ $errors->first('name') }}</span>
                        @endif
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Email</label>
                        <input type="email" class="form-control", name="email">
                        @if ($errors->has('email'))
                            <span>{{ $errors->first('email') }}</span>
                        @endif
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Access</label>
                        <select name="access_id">
                            @foreach ($accesses as $item )
                            <option value="{{ $item->id }}">{{ $item->name }}</option>    
                            @endforeach
                        </select>
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/user/editUser.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    Edit User
                    
                </div>
                <div class="card-body">
                    
                <form action="{{ route('user.update', $Users->id )}}" method="post">
                    @csrf
                    @method('PUT')
                    <div class="mb-3">
                        <label class="form-label">Name</label>
                        <input type="text" class="form-control" name="name" value="{{ $Users->name }}">
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Email</label>
                        <input type="email" class="form-control" name="email" value="{{ $Users->email }}">
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Access</label>
                        <select name="access_id">
                            @foreach ($accesses as $item )
                            <option {{ $item->id == $Users->access_id ? "selected" : "" }} value="{{ $item->id }}">{{ $item->name }}</option>    
                            @endforeach
                            <!-- 
                            <option value="1">Owner</option>    
                            <option value="2">Admin</option>    
                            <option value="1">Member</option>     -->
                        </select>
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/user/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container" id = "user-index">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    Users
                    <a href="{{ route('user.create')}}" type="button" class="btn btn-primary" style="float: right">Add User</a>
                </div>
                <div class="card-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Name</th>
                                <th scope="col">Email</th>
                                <th scope="col">Access</th>
                                <th scope="col">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($users as $item)
                            <tr>
                                <th scope="row">{{ $item->id }}</th>
                                <td>{{ $item->name }}</td>
                                <td>{{ $item->email }}</td>
                                <td>
                                    {{ $item->access->name ?? '-' }}
                                </td>
                                <td>
                                    <a href="{{ route('user.edit', ['user'=> $item->id]  )}}" type="button" class="btn btn-success">Edit</a>
                                    <a href="{{ route('user.show', $item->id )}}" type="button" class="btn btn-secondary">Show</a>
                                    
                                    <form action="{{ route('user.update', $item->id) }}" method="POST">
                                        @csrf
                                        @method('delete')
                                        <button type="submit" class="btn btn-danger">Delete</button>
                                    </form>
                                </td>
                            </tr>                               
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/user/showUser.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
    
    <div class="card shadow mb-4">
        <div class="card header py-3">
            <div class="row">
                <div class="col d-flex align-item-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">Users</h6>
                <div>
            </div>
        </div>
        <div class="card-body">

            <div class="form-body">
                <div class="row">
                    <div class="col-md-8">
                        <div class="form-group row">
                            <label class="col-md-2 label-control text-left">Name</label>
                            <div class="col-md-10">
                                <p>{{ $Users->name }}</p>
                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-body">
                <div class="row">
                    <div class="col-md-8">
                        <div class="form-group row">
                            <label class="col-md-2 label-control text-left">Email</label>
                            <div class="col-md-10">
                            <p>{{ $Users->email }}</p>
                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-body">
                <div class="row">
                    <div class="col-md-8">
                        <div class="form-group row">
                            <label class="col-md-2 label-control text-left">Access</label>
                            <div class="col-md-10">
                            <p>{{ $Users->access_id }}</p>
                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-body">
                <div class="row">
                    <div class="col-md-8">
                        <div class="form-group row">
                            <label class="col-md-2 label-control text-left"></label>
                            <div class="col-md-10">
                                <a type="btn" class="btn btn-md btn-secondary" href="{{ route('user.index') }}">Back</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
                
        </div>
    </div>
</div>
@endsection